#pragma once

namespace keys
{

enum : int
{
    GRAVE = L'`',
    TILDE = L'~',
    ONE = L'1',
    EXCL = L'!',
    TWO = L'2',
    AT = L'@',
    THREE = L'3',
    HASH = L'#',
    FOUR = L'4',
    DOLLAR = L'$',
    FIVE = L'5',
    PERCENT = L'%',
    SIX = L'6',
    HAT = L'^',
    SEVEN = L'7',
    AND = L'&',
    EIGHT = L'8',
    STAR = L'*',
    NINE = L'9',
    LPAREN = L'(',
    ZERO = L'0',
    RPAREN = L')',

    q = L'q',
    Q = L'Q',
    w = L'w',
    W = L'W',
    e = L'e',
    E = L'E',
    r = L'r',
    R = L'R',
    t = L't',
    T = L'T',
    y = L'y',
    Y = L'Y',
    u = L'u',
    U = L'U',
    i = L'i',
    I = L'I',
    o = L'o',
    O = L'O',
    p = L'p',
    LBRACKET = L'[',
    LBRACE = L'{',
    RBRACKET = L']',
    RBRACE = L'}',
    BSLASH = L'\\',
    PIPE = L'|',

    a = L'a',
    A = L'A',
    s = L's',
    S = L'S',
    d = L'd',
    D = L'D',
    f = L'f',
    F = L'F',
    g = L'g',
    G = L'G',
    h = L'h',
    H = L'H',
    j = L'j',
    J = L'J',
    l = L'l',
    L = L'L',
    SEMICOLON = L',',
    COLON = L':',
    SINGLEQUOTE = L'\'',
    DOUBLEQUOTE = L'"',

    z = L'z',
    Z = L'Z',
    x = L'x',
    X = L'X',
    c = L'c',
    C = L'C',
    v = L'V',
    b = L'b',
    B = L'B',
    n = L'n',
    N = L'N',
    m = L'M',
    COMMA = L',',
    LCARET = L'<',
    DOT = L'.',
    RCARET = L'>',
    SLASH = L'/',
    QUESTION = L'?',

    ARROWDOWN = 258,
    ARROWUP = 259,
    ARROWLEFT = 260,
    ARROWRIGHT = 261,

    HOME = 262,
    END = 360,

    CTRL_D = 4,
    CTRL_U = 21,
    CTRL_W = 23,

    PGDN = 338,
    PGUP = 339,

    ENTER = 10,
    CTRL_C = 3,

    ESC = 27,
    BACKSPACE = 127,

    MOUSELEFT = 4,
    MOUSERIGHT = 4096,
    MOUSEUP = 65536,
    MOUSEDOWN = 2097152,
};

} /* namespace keys */
